services:
  mongo:
    image: mongo:7
    container_name: mindfit-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mindfit}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - mindfit-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build:
      context: ./mindfit-api
      dockerfile: Dockerfile
    container_name: mindfit-api
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: production
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/mindfit}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-api-key}
      JWT_SECRET: ${JWT_SECRET:-mySecretKeyForDevelopmentPleaseChangeInProduction123456789012345678901234567890}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS:-http://localhost:8082,http://localhost:8083}
    ports:
      - "8088:8080"
    networks:
      - mindfit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  admin:
    build:
      context: ./mindfit-admin-panel
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL:-http://localhost:8088}
    container_name: mindfit-admin-panel
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8082:80"
    networks:
      - mindfit-network

  app:
    build:
      context: ./mindfit-app
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL:-http://localhost:8088}
    container_name: mindfit-app
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8083:80"
    networks:
      - mindfit-network

networks:
  mindfit-network:
    driver: bridge

volumes:
  mongo_data:
