spring:
  application:
    name: Mindfit API
  data:
    mongodb:
      uri: mongodb://localhost:27017/mindfit
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        options:
          model: gpt-4.1-nano

server:
  tomcat:
    max-http-request-header-size: 8KB
    max-http-form-post-size: 2MB
    connection-timeout: 5000
    reject-illegal-header: true
  error:
    include-stacktrace: never
    include-message: never

app:
  jwt:
    secret: mySecretKeyForDevelopmentPleaseChangeInProduction
    expiration-ms: 86400000
  cors:
    # Comma-separated list of allowed origins for CORS (adjust as needed)
    allowed-origins: http://localhost:4200,http://localhost:3000,http://localhost:5173

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.mindfit: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/mindfit}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

app:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration-ms: 86400000
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000,http://localhost:5173}

logging:
  level:
    com.mindfit: INFO
