spring:
  application:
    name: Mindfit API
  data:
    mongodb:
      uri: mongodb://localhost:27017/mindfit
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        options:
          model: gpt-4.1-mini

app:
  jwt:
    secret: mySecretKeyForDevelopmentPleaseChangeInProduction
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.mindfit: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/mindfit}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

app:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration-ms: 86400000

logging:
  level:
    com.mindfit: INFO