version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mindfit-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mindfit

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mindfit-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8085:8081"
    depends_on:
      - mongo

volumes:
  mongo_data: